### ISSUE TITLE
feat: Create notebook to generate Naas Chat plugin with the commands

### ISSUE THREAD

**Issue by Dr0p42** [jupyter-naas/engine-content#9]
We need to have a way to install the commands to interact with this workflow.

- Command to send the youtube URL. Refer to the main issue.
- Command to store cookies to naas secret.

**Comment by FlorentLvr** [comment]
Notebook done, commands to be adapted: 
<img width="448" alt="image" src="https://github.com/jupyter-naas/engine-content/assets/48032461/e07fdb65-d096-4f0c-b672-2ebcd1f1216f">
